config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins

  root 'ethnic_churches#index'

  get 'languages/:id' => 'languages#show', as: :language
  get 'attributions' => 'pages#attributions', as: :attributions

  resources :ethnic_churches
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :ethnic_church

  def full_address
    return "#{street}\n#{city}, CA #{zip}" if street.present? && city.present? && zip.present?
    return "#{street}\n#{city}, CA" if street.present? && city.present?
    return "#{city}, CA" if city.present?
    'CA'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :ethnic_churches

  validates :name, uniqueness: true
end

app/models/ethnic_church.rb
class EthnicChurch < ApplicationRecord
  has_many :services
  has_many :languages, through: :services
  has_one :address
  has_one :note
  belongs_to :country
  belongs_to :religious_background

  validates :email, format: { with: Devise.email_regexp }, allow_nil: true
end

app/models/ethnic_church_builder.rb
class EthnicChurchBuilder
  def self.instantiate(objects)
    @ec = objects[:ethnic_church]
    @ec.languages = objects[:languages]
    @ec.country = objects[:country]
    @ec.religious_background = objects[:religious_background]
    @ec.address = objects[:address]
    @ec.note = objects[:note]
    @ec
  end
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :services
  has_many :ethnic_churches, through: :services

  validates :name, uniqueness: true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :ethnic_church
end

app/models/religious_background.rb
class ReligiousBackground < ApplicationRecord
  has_many :ethnic_churches

  validates :persuasion, uniqueness: true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :ethnic_church
  belongs_to :language
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ethnic_churches_controller.rb
class EthnicChurchesController < ApplicationController
  before_action :authenticate_admin!, only: %i[new create edit update]

  def index
    @ethnic_churches = EthnicChurch.page(params[:page])
    @languages = Language.order(:name)
  end

  def show
    @ethnic_church = EthnicChurch.find(params[:id])
  end

  def new
    @ethnic_church = EthnicChurch.new
  end

  def create
    @ethnic_church = EthnicChurchBuilder.instantiate(
      ethnic_church: ethnic_church,
      languages: languages,
      country: country,
      religious_background: religious_background,
      address: address,
      note: note
    )

    if @ethnic_church.save
      redirect_to ethnic_church_path(@ethnic_church), notice: 'Successfully added new Ethnic Church'
    else
      flash.now.alert = @ethnic_church.errors.full_messages.join(', ')
      render 'new'
    end
  end

  def edit
    @ethnic_church = EthnicChurch.find(params[:id])
  end

  def update
    @ethnic_church = EthnicChurchBuilder.instantiate(
      ethnic_church: ethnic_church,
      languages: languages,
      country: country,
      religious_background: religious_background,
      address: address,
      note: note
    )

    if @ethnic_church.save
      redirect_to ethnic_church_path(@ethnic_church), notice: 'Successfully updated Ethnic Church'
    else
      flash.now.alert = @ethnic_church.errors.full_messages.join(', ')
      render 'new'
    end
  end

  private

  def ethnic_church
    ec = EthnicChurch.find_by(id: params[:id]) || EthnicChurch.new
    ec.assign_attributes(ethnic_church_params)
    ec
  end

  def languages
    params[:ethnic_church][:language][:name].reject(&:blank?).map do |lang_name|
      Language.find_or_initialize_by(name: lang_name)
    end
  end

  def country
    country = params[:ethnic_church][:country][:name]
    Country.find_or_initialize_by(name: country)
  end

  def address
    addr = ethnic_church.address || ethnic_church.build_address(address_params)
    addr.assign_attributes(address_params)
    addr
  end

  def note
    n = ethnic_church.note || ethnic_church.build_note(note_params)
    n.assign_attributes(note_params)
    n
  end

  def note_params
    params.require(:ethnic_church).require(:note).permit(:content)
  end

  def religious_background
    persuasion = params[:ethnic_church][:religious_background][:persuasion]
    ReligiousBackground.find_or_initialize_by(persuasion: persuasion)
  end

  def ethnic_church_params
    params.require(:ethnic_church)
      .permit(:name, :phone, :website, :pastors_name, :email)
      .transform_values { |val| val if val.present? }
  end

  def address_params
    params.require(:ethnic_church).require(:address).permit(:street, :city, :zip)
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def show
    @language = Language.find_by(id: params[:id])
    @ethnic_churches = @language.ethnic_churches.page(params[:page])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def attributions
    @attributions = YAML.load_file('config/attributions.yml')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_footer?
    return true unless %w[sessions passwords].include?(controller_name)
    return false
  end
end

app/helpers/ethnic_churches_helper.rb
module EthnicChurchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ethnic_churches/_form.html.haml
.row.justify-content-center
  .jumbotron.col-9
    = form_for @ethnic_church, html: { class: 'form-group' } do |f|
      = f.label :name
      = f.text_field :name
      = f.label :phone
      = f.text_field :phone
      = f.label :website
      = f.text_field :website
      = f.label :pastors_name
      = f.text_field :pastors_name
      = f.label :email
      = f.text_field :email
      = f.fields_for :language do |lang|
        = lang.label :language
        = lang.collection_select :name, Language.order(:name), :name, :name, { selected: @ethnic_church.languages.pluck(:name) }, multiple: true
      = f.fields_for :country, @ethnic_church.country do |country|
        = country.label :country
        = country.text_field :name
      = f.fields_for :religious_background, @ethnic_church.religious_background do |religious_background|
        = religious_background.label :religious_background
        = religious_background.text_field :persuasion
      = f.fields_for :address, @ethnic_church.address do |address|
        = address.label :street
        = address.text_field :street
        = address.label :city
        = address.text_field :city
        = address.label :zip
        = address.text_field :zip
      = f.fields_for :note, @ethnic_church.note do |note|
        = note.label :note
        = note.text_area :content
      = f.submit (@ethnic_church.new_record? ? 'Create' : 'Update'), class: 'btn btn-primary', id: 'create'

app/views/ethnic_churches/_list.html.haml
%table{class: 'table table-striped'}
  %thead
    %tr
      %th
        %strong Church Name
      %th Language
      %th City
      %th Website
  %tbody
    - @ethnic_churches.each do |church|
      %tr
        %td= link_to(church.name, ethnic_church_path(church))
        %td.language-name= church.languages.map(&:name).join(', ')
        %td= church.address.city
        %td= church.website
= paginate @ethnic_churches

app/views/ethnic_churches/edit.html.haml
= render 'form'

app/views/ethnic_churches/index.html.haml
= render 'languages/list'

app/views/ethnic_churches/new.html.haml
.row.justify-content-center
  .jumbotron.col-9
    .col-2
      = form_for @ethnic_church do |f|
        = f.label :name
        = f.text_field :name
        = f.label :phone
        = f.text_field :phone
        = f.label :website
        = f.text_field :website
        = f.label :pastors_name
        = f.text_field :pastors_name
        = f.label :email
        = f.text_field :email
        = f.fields_for :language do |lang|
          = lang.label :language
          = lang.collection_select :name, Language.order(:name), :name, :name, {}, multiple: true
        = f.fields_for :country do |country|
          = country.label :name, 'Country'
          = country.text_field :name
        = f.fields_for :religious_background do |religious_background|
          = religious_background.label :religious_background
          = religious_background.text_field :persuasion
        = f.fields_for :address do |address|
          = address.label :street
          = address.text_field :street
          = address.label :city
          = address.text_field :city
          = address.label :zip
          = address.text_field :zip
        = f.fields_for :note do |note|
          = note.label :note
          = note.text_field :content
        = f.submit 'Create', class: 'btn btn-primary', id: 'create'

app/views/ethnic_churches/show.html.haml
.row.justify-content-center
  .jumbotron.col-9
    - if @ethnic_church.unconfirmed
      %p.alert.alert-warning The existence of this church cannot be confirmed.
    %h2#church_name= @ethnic_church.name
    %h3.title-with-emphasis Website:
    %p#website= @ethnic_church.website || '-'

    %h3.title-with-emphasis Address:
    #address= simple_format(@ethnic_church.address.full_address || '-')

    %h3.title-with-emphasis Phone:
    %p#phone= @ethnic_church.phone || '-'

    %h3.title-with-emphasis Email:
    %p#email= @ethnic_church.email || '-'

    %h3.title-with-emphasis Pastor:
    %p#pastors_name= @ethnic_church.pastors_name || '-'

    %h3.title-with-emphasis Languages:
    %p#language= @ethnic_church.languages.map(&:name).join(', ') || '-'

    %h3.title-with-emphasis Associated Country:
    %p#country= @ethnic_church.country.name || '-'

    %h3.title-with-emphasis Religious Background:
    %p#religious_background= @ethnic_church.religious_background.persuasion || '-'

    %h3.title-with-emphasis Notes:
    #note= simple_format(@ethnic_church.note.try(:content) || '-')

    %p= link_to 'Edit', edit_ethnic_church_path(@ethnic_church)

app/views/languages/_list.html.haml
.language_list
  - @languages.each do |lang|
    .language{ class: "#{lang.name.parameterize} #{cycle('diamond-tiles', 'dingy-yellow-wall')}" }
      = link_to(language_path(lang.id)) do
        %p.lang-endonym= lang.endonym
        %p= lang.name || 'Unknown'

app/views/languages/_map.js.erb
mapboxgl.accessToken = 'pk.eyJ1IjoiZXRobmljbGEiLCJhIjoiY2psZTM1Z3dnMGh1aTNrb3lnb3YzZzMzeSJ9.5HGT4cTIUGjgFrfJGW0bXg';
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/ethnicla/cjlhdx9ii05o82rp9w6r1008s',
    center: [-118, 33.91],
    zoom: 8.5
});

map.scrollZoom.disable();

map.on('load', function() {
    map.addSource('language-map', {
        "type": "geojson",
        "data": {
          "type": "FeatureCollection",
          "features": [
            <%- @language.ethnic_churches.find_each do |ec| %>
            { "type": "Feature", "geometry": { "type": "Point", "coordinates": [ <%= ec.address.longitude %>, <%= ec.address.latitude %> ] } },
            <%- end %>
            { "type": "Feature", "geometry": { "type": "Point", "coordinates": [ ] } }
          ]
        }
    });

    map.addLayer({
        "id": "language-heatmap",
        "type": "heatmap",
        "source": "language-map",
        "paint": {
          "heatmap-weight": 0.54,
          "heatmap-radius": 17,
          "heatmap-color": [
              "interpolate",
              [
                  "linear"
              ],
              [
                  "heatmap-density"
              ],
              0,
              "rgba(0, 0, 255, 0)",
              0.1,
              "hsl(225, 73%, 57%)",
              0.3,
              "cyan",
              0.5,
              "lime",
              0.7,
              "yellow",
              1,
              "red"
          ]

        }
    });

});

app/views/languages/show.html.haml
%main
  %h2{class: 'mb-5'}
    - if @language
      = @language.name
      = ' - '
    = 'Los Angeles Area Ethnic Churches'
  #map
  %script
    = render partial: 'map', formats: [:js]
  = render 'ethnic_churches/list'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ethnic LA
    = csrf_meta_tags
    = stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Passion+One', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'ethnic_churches_form', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://api.tiles.mapbox.com/mapbox-gl-js/v0.48.0/mapbox-gl.js'
    = stylesheet_link_tag    'https://api.tiles.mapbox.com/mapbox-gl-js/v0.48.0/mapbox-gl.css'
  %body
    = link_to(root_path, class: 'logo-text') do
      %header
        = image_tag 'koreanbell.png', size: '300x164', class: 'logo-image'
        %p.logo Ethnic LA
        %p.subtitle
          %strong
            = 'Facilitating the discovery of languages, cultures'
            %br
            = 'and ethnic groups in the Los Angeles area'
    .row.justify-content-center
      .col-9
        - if notice
          %p#notice.alert.alert-success
            = notice
        - if alert
          %p#alert.alert.alert-danger
            = alert
    = yield
    - if show_footer?
      %footer
        - if admin_signed_in?
          = link_to('Logout', destroy_admin_session_path, id: 'logout', method: :delete)
        - else
          = link_to('Admin Login', new_admin_session_path, id: 'login')
        = ' - '
        = link_to('Attributions', attributions_path)
        = ' - '
        = link_to('Source Code', 'https://github.com/ericmathison/ethnic_la')

app/views/pages/attributions.html.haml
.jumbotron.col-9
  %h1.text-center Attributions
  %h2 Language Image Credits:

  - @attributions.each do |language, url|
    %h3.title-with-emphasis= language
    %p= link_to(url, url)